name: Show dates
on: push

jobs:
  job1:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Show the date
      run: date
  job2:
    name: windows
    runs-on: windows-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Show the date
      run: date
  job3:
    name: macos
    runs-on: macos-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Show the date
      run: date

  job4:
    name: ubuntu 20.04
    needs: [job1, job2, job3]
    runs-on: ubuntu-20.04
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Show the date
      run: date


